baseurl = "https://alister.github.io"
disablePathToLower = false
languageCode = "en-gb"
title = "Professional Blog"
theme = "Hugo-Octopress"

enableRobotsTXT = true
sectionPagesMenu = "main"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# Note it's not under [params] anymore
# disqusShortname = "Your disqus shortname"

# Number of blog posts in each pagination page
paginate = 8

[permalinks]
post = "/:title/" # change the post URL to look like the old ones
blog = "/blog/:year/:month/:day/:title/"

[markup]
  # Default is startLevel 2 and endLevel 3, we want to render every heading
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  # set the Chroma highlighting options
  # https://gohugo.io/getting-started/configuration-markup/#highlight
  # https://xyproto.github.io/splash/docs/all.html
  [markup.highlight]
    style = "monokai"

# https://gohugo.io/templates/sitemap-template/#configure-sitemapxml
[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5


[params]

  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 4

  # Sidebar header - passed to markdownify so you can write markdown here
  sidebarHeader = "Sidebar"

  # Sidebar text also supports markdown
  # New lines can be added with two spaces at the end of line. New paragraphs can be added with two an empty line.
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  sidebarText = """Re-created with Hugo, August 2021.
  """
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = true
  # sidebarMenuHeader = "Links"

  # sidebar links
  home = "https://abulman.co.uk"
  github = "https://github.com/alister"
  # twitter = "https://twitter.com/alister_b/"
  stackoverflow = "https://stackoverflow.com/users/6216/alister-bulman"
  linkedin = "https://www.linkedin.com/in/alisterbulman"
  blog = "https://www.phpscaling.com/"
  mastodon = "https://hachyderm.io/@alister"
  fediverse_creator = "@Alister@hachyderm.io"

  # bitbucket = "https://bitbucket.org/alisterb/"
  # youtube = ""
  #keybase = ""
  #facebook = ""
  #instagram = ""

  # --- End sidebar options ---

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or set to false, then navigation menu links will open in the same window
  navigationNewWindow = false

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Alister Bulman"

  # This text appears in the site header under website title
  subtitle = "A few things I've been up to"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Continue reading &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-37346894-1"

  # Optional piwik tracking
  # [params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = ""

  # Populate this with your own search keywords - these will appear in the meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # CSS override files
  # Paths should be relative to the `static` directory
  # customCSS = ["css/custom.css","css/custom2.css"]

  # 404.html header and text - both support markdown
  notFoundHeader = "There's nothing here"

  notFoundText = """Please either go back or use the navigation/sidebar menus.
  """

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or Set to false to use local fonts
  # remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # Generate taxonomy pages
  generateTaxonomyList = true

  # This is not needed unless alphabetical sort is needed
  # sortTaxonomyAlphabetical = true

  # Twitter card config
  # Enable with this.
  twitterCardEnabled = true
  # Don't include the @.
  # twitterCardSite =
  twitterCardDomain = "alister.github.io"
  # Don't include the @.
  twitterCardAuthor = "alister_b"

  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  compactIndex = false

  # Set mainSections.
  mainSections = ["post", "blog"]

# Menu
# If navigationNewWindow (under [params]) is set to true then all links except root ("/") will open in a new window
# If it does not exist or is set to false then links will open in the same window
# [[menu.main]]
#   Name = "Blog"
#   URL = "/"
#   weight = -50

[[menu.main]]
  Name = "Presentations"
  URL = "presentations/"
  weight = 10

[[menu.main]]
  Name = "Projects"
  URL = "projects/"
  weight = 20


# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]
# [[menu.sidebar]]
#   Name = "Alister"
#   URL = "https://abulman.co.uk"
#   weight = 0

# [[menu.sidebar]]
#   Name = "Hugo category"
#   URL = "/categories/golang/"
#   weight = 1

# [[menu.sidebar]]
#   Name = "About"
#   URL = "/about"
#   weight = 2

# from https://decovar.dev/blog/2019/03/17/migrating-from-octopress-to-hugo/#migration-from-octopress-to-hugo
# disableKinds = ["taxonomyTerm"]
# preserveTaxonomyNames = true
# [taxonomies]
#     tag = "tags"
#     category = "categories"

# from: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = false
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[privacy.instagram]
disable = false
simple = true

[privacy.twitter]
disable = false
enableDNT = true
simple = true

[privacy.vimeo]
disable = false
enableDNT = true
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true
